// Generated by CoffeeScript 1.7.1
(function() {
  var flatPricing;

  flatPricing = angular.module("flatPricing", []);

  flatPricing.controller("flatPricingController", function($scope) {
    $scope.computers = 1;
    $scope.baseRate = 100;
    return $scope.totalRate = $scope.baseRate;
  });

}).call(this);

//# sourceMappingURL=flat-pricing.map
