// Generated by CoffeeScript 1.7.1
(function() {
  var flatPricing;

  flatPricing = angular.module("flatPricing", ["ngAnimate", "slide"]);

  flatPricing.controller("flatPricingController", function($scope) {
    $scope.show = {};
    return $scope.showContact = function() {
      $scope.show.contact = true;
      return setTimeout(function() {
        return window.scrollTo(0, document.body.scrollHeight);
      }, 50);
    };
  });

}).call(this);

//# sourceMappingURL=flat.map
