// Generated by CoffeeScript 1.7.1
(function() {
  var flatPricing;

  flatPricing = angular.module("flatPricing", ["ngAnimate", "slide"]);

  flatPricing.controller("flatPricingController", function($scope) {
    return $scope.show = {};
  });

}).call(this);

//# sourceMappingURL=flat-pricing.map
