// Generated by CoffeeScript 1.7.1
(function() {
  var slide;

  slide = angular.module("slide", ['ngAnimate']);

  slide.animation('.slide', function() {
    var NgHideClassName;
    NgHideClassName = 'ng-hide';
    return {
      beforeAddClass: function(element, className, done) {
        if (className === NgHideClassName) {
          return jQuery(element).slideUp(done);
        }
      },
      removeClass: function(element, className, done) {
        if (className === NgHideClassName) {
          return jQuery(element).hide().slideDown(done);
        }
      }
    };
  });

}).call(this);

//# sourceMappingURL=utils.map
